version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  target-branch: "main"
  schedule:
    interval: "weekly"
    day: "monday"
  cooldown:
    default-days: 7
  open-pull-requests-limit: 10
  groups:
    all-go-mod:
      patterns: [ "*" ]
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: "main"
  schedule:
    interval: "weekly"
    day: "monday"
  cooldown:
    default-days: 7
  open-pull-requests-limit: 10
  groups:
    all-github-actions:
      patterns: [ "*" ]
- package-ecosystem: gomod
  directory: "/"
  target-branch: "v2"
  schedule:
    interval: "weekly"
    day: "monday"
  cooldown:
    default-days: 7
  open-pull-requests-limit: 10
  groups:
    all-go-mod:
      patterns: [ "*" ]
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: "v2"
  schedule:
    interval: "weekly"
    day: "monday"
  cooldown:
    default-days: 7
  open-pull-requests-limit: 10
  groups:
    all-github-actions:
      patterns: [ "*" ]
