- color: '9E1957'
  description: Breaking change
  name: semver:major
- color: 'FBCA04'
  description: Backwards-compatible change
  name: semver:minor
- color: '6E7624'
  description: No API change
  name: semver:patch
- color: '30ABB9'
  description: This PR will be backported to v1
  name: backport-v1
- color: 'BCF611'
  description: A good issue for first-time contributors
  name: good first issue
