- project:
    name: theopenlab/gophercloud
    check:
      jobs:
        - gophercloud-unittest
        - gophercloud-acctest
    recheck-mitaka:
      jobs:
        - gophercloud-acctest-mitaka
    recheck-pike:
      jobs:
        - gophercloud-acctest-pike
