- project:
    name: theopenlab/gophercloud
    check:
      jobs:
        - gophercloud-telefonica-acceptance-test
    recheck-mitaka:
      jobs:
        - gophercloud-acceptance-test-mitaka
    recheck-pike:
      jobs:
        - gophercloud-acceptance-test-pike
