- project:
    name: theopenlab/gophercloud
    check:
      jobs:
        - gophercloud-unittest
        - gophercloud-acceptance-test
    recheck-mitaka:
      jobs:
        - gophercloud-acceptance-test-os-mitaka
    recheck-pike:
      jobs:
        - gophercloud-acceptance-test-os-pike
