- hosts: all
  tasks:
    - name: Run unit tests with gophercloud
      shell:
        cmd: |
          set -e
          set -o pipefail
          set -x

          if [[ ! -d $GOPATH/src/github.com/gophercloud/gophercloud/ && -d $GOPATH/src/github.com/theopenlab/gophercloud ]]; then
              echo "Warning: this is a temporary workaround because this job is not triggered from official git repo."
              mkdir -p $GOPATH/src/github.com/gophercloud/
              cp -r $GOPATH/src/github.com/theopenlab/gophercloud  $GOPATH/src/github.com/gophercloud/
              cd $GOPATH/src/github.com/gophercloud/gophercloud
          fi

          go get ./... || true
          ./script/unittest -v 2>&1 | tee $TEST_RESULTS_TXT
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env }}'
