#!/bin/bash
#
# Run the unit tests.

set -euxo pipefail

# Do extra rounds of testing to help identify reauth concurrency issues.
# All other packages are tested in the `coverage` tests.
# shellcheck disable=SC2068
go test -v -race -count=5 ./testing $@
