name: Pull Request backporting

on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backporting:
    name: "Backporting"
    # Only react to merged PRs for security reasons.
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
    if: >
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
          && contains(github.event.pull_request.labels.*.name, 'backport-v2')
        || (
          github.event.action == 'labeled'
          && contains(github.event.label.name, 'backport-v2')
        )
      )
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token from the gophercloud-backport-bot github-app
        id: generate_token
        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc
        with:
          app_id: ${{ secrets.BACKPORT_APP_ID }}
          private_key: ${{ secrets.BACKPORT_APP_PRIVATE_KEY }}

      - name: Backporting
        if: >
          contains(github.event.pull_request.labels.*.name, 'semver:patch')
          || contains(github.event.pull_request.labels.*.name, 'semver:minor')
          || contains(github.event.label.name, 'semver:patch')
          || contains(github.event.label.name, 'semver:minor')
        uses: kiegroup/git-backporting@c22286f85e0a14ebb66755b381163ab9cd8310fa
        with:
          target-branch: v2
          pull-request: ${{ github.event.pull_request.url }}
          auth: ${{ steps.generate_token.outputs.token }}
          no-squash: true
          strategy-option: find-renames

      - name: Report failure
        if: failure()
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          BODY: >
            Failed to backport PR to `v2` branch. See [logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.

      - name: Report an error if backport unsupported labels
        if: >
          contains(github.event.pull_request.labels.*.name, 'semver:major')
          || contains(github.event.pull_request.labels.*.name, 'semver:unknown')
          || contains(github.event.label.name, 'semver:major')
          || contains(github.event.label.name, 'semver:unknown')
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6
        with:
          message: |
            Labels `semver-major` or `semver-unknown` can not trigger backports.
            The PR has to be labeled `semver-patch` or `semver-minor`.
