name: functional-compute
on:
  pull_request:
    paths:
      - 'openstack/auth_env.go'
      - 'openstack/client.go'
      - 'openstack/endpoint.go'
      - 'openstack/endpoint_location.go'
      - 'openstack/config/provider_client.go'
      - 'openstack/utils/choose_version.go'
      - 'openstack/utils/discovery.go'
      - '**compute**'
      - '.github/workflows/functional-compute.yaml'
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  functional-compute:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "master"
            openstack_version: "master"
            ubuntu_version: "24.04"
            additional_services: "openstack-cli-server"
          - name: "epoxy"
            openstack_version: "stable/2025.1"
            ubuntu_version: "22.04"
            additional_services: "openstack-cli-server"
          - name: "dalmatian"
            openstack_version: "stable/2024.2"
            ubuntu_version: "22.04"
            additional_services: "openstack-cli-server"
          - name: "caracal"
            openstack_version: "stable/2024.1"
            ubuntu_version: "22.04"
            additional_services: ""
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: Nova on OpenStack ${{ matrix.name }}
    steps:
      - name: Checkout Gophercloud
        uses: actions/checkout@v4

      - name: Run functional tests
        uses: ./.github/actions/functional-test
        with:
          target: "compute"
          openstack_version: ${{ matrix.openstack_version }}
          additional_services: ${{ matrix.additional_services }}
          conf_overrides: |
            CINDER_ISCSI_HELPER=lioadm
