name: functional-metric
on:
  pull_request:
    paths:
      - 'openstack/auth_env.go'
      - 'openstack/client.go'
      - 'openstack/endpoint.go'
      - 'openstack/endpoint_location.go'
      - 'openstack/config/provider_client.go'
      - 'openstack/utils/choose_version.go'
      - 'openstack/utils/discovery.go'
      - '**metric**'
      - '.github/workflows/functional-metric.yaml'
  schedule:
    - cron: '0 0 */3 * *'
jobs:
  functional-metric:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "master"
            openstack_version: "master"
            ubuntu_version: "24.04"
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: Aetos on OpenStack ${{ matrix.name }}
    steps:
      - name: Checkout Gophercloud
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Deploy devstack
        uses: gophercloud/devstack-action@60ca1042045c0c9e3e001c64575d381654ffcba1 # v0.19
        with:
          branch: ${{ matrix.openstack_version }}
          conf_overrides: |
            enable_plugin devstack-plugin-prometheus https://github.com/openstack/devstack-plugin-prometheus ${{ matrix.openstack_version }}
            enable_plugin ceilometer https://github.com/openstack/ceilometer ${{ matrix.openstack_version }}
            CEILOMETER_BACKEND=sg-core
            PROMETHEUS_CUSTOM_SCRAPE_TARGETS="localhost:3000"
            enable_plugin sg-core https://github.com/openstack-k8s-operators/sg-core main
            enable_plugin aetos https://github.com/openstack/aetos ${{ matrix.openstack_version }}

            ${{ matrix.devstack_conf_overrides }}
          enabled_services: "prometheus,node_exporter,openstack_exporter,ceilometer-acompute,ceilometer-acentral,ceilometer-anotification,sg-core,aetos,openstack-cli-server"

      - name: Checkout go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run Gophercloud acceptance tests
        run: |
          source ${{ github.workspace }}/script/stackenv
          make acceptance-metric
        env:
          DEVSTACK_PATH: ${{ github.workspace }}/devstack
          OS_BRANCH: ${{ matrix.openstack_version }}

      - name: Generate logs on failure
        run: ./script/collectlogs
        if: failure()

      - name: Upload logs artifacts on failure
        if: failure()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: functional-metric-${{ matrix.name }}-${{ github.run_id }}
          path: /tmp/devstack-logs/*
