name: functional-workflow
on:
  pull_request:
    paths:
      - '**workflow**'
      - '.github/workflows/functional-workflow.yaml'
  schedule:
    - cron: '0 0 */3 * *'
jobs:
  functional-workflow:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "master"
            openstack_version: "master"
            ubuntu_version: "24.04"
            mistral_plugin_version: "master"
            additional_services: "openstack-cli-server"
          - name: "epoxy"
            openstack_version: "stable/2025.1"
            ubuntu_version: "22.04"
            mistral_plugin_version: "stable/2025.1"
            additional_services: "openstack-cli-server"
          - name: "dalmatian"
            openstack_version: "stable/2024.2"
            ubuntu_version: "22.04"
            mistral_plugin_version: "stable/2024.2"
            additional_services: "openstack-cli-server"
          - name: "caracal"
            openstack_version: "stable/2024.1"
            ubuntu_version: "22.04"
            mistral_plugin_version: "stable/2024.1"
            additional_services: ""
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: Deploy OpenStack ${{ matrix.name }} with Mistral and run workflow acceptance tests
    steps:
      - name: Checkout Gophercloud
        uses: actions/checkout@v4
      - name: Deploy devstack
        uses: gophercloud/devstack-action@v0.18
        with:
          branch: ${{ matrix.openstack_version }}
          conf_overrides: |
            enable_plugin mistral https://github.com/openstack/mistral ${{ matrix.mistral_plugin_version }}
          enabled_services: "mistral,mistral-api,mistral-engine,mistral-executor,mistral-event-engine,${{ matrix.additional_services }}"
      - name: Checkout go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23'
      - name: Run Gophercloud acceptance tests
        run: |
          source ${{ github.workspace }}/script/stackenv
          make acceptance-workflow
        env:
          DEVSTACK_PATH: ${{ github.workspace }}/devstack
          OS_BRANCH: ${{ matrix.openstack_version }}
      - name: Generate logs on failure
        run: ./script/collectlogs
        if: failure()
      - name: Upload logs artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: functional-workflow-${{ matrix.name }}-${{ github.run_id }}
          path: /tmp/devstack-logs/*
