name: functional-clustering
on:
  pull_request:
    paths:
      - '**clustering**'
  schedule:
    - cron: '0 0 * * *'
jobs:
  functional-clustering:
    strategy:
      fail-fast: false
      matrix:
        name: ["master"]
        openstack_version: ["master"]
        ubuntu_version: ["20.04"]
        include:
          - name: "yoga"
            openstack_version: "stable/yoga"
            ubuntu_version: "20.04"
          - name: "xena"
            openstack_version: "stable/xena"
            ubuntu_version: "20.04"
          - name: "wallaby"
            openstack_version: "stable/wallaby"
            ubuntu_version: "20.04"
          - name: "victoria"
            openstack_version: "stable/victoria"
            ubuntu_version: "20.04"
          - name: "ussuri"
            openstack_version: "stable/ussuri"
            ubuntu_version: "18.04"
          - name: "train"
            openstack_version: "stable/train"
            ubuntu_version: "18.04"
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: Deploy OpenStack ${{ matrix.name }} with Senlin and run clustering acceptance tests
    steps:
      - name: Checkout Gophercloud
        uses: actions/checkout@v3
      - name: Deploy devstack
        uses: EmilienM/devstack-action@v0.10
        with:
          branch: ${{ matrix.openstack_version }}
          conf_overrides: |
            enable_plugin senlin https://opendev.org/openstack/senlin ${{ matrix.openstack_version }}
            enable_plugin zaqar https://opendev.org/openstack/zaqar ${{ matrix.openstack_version }}
            ZAQARCLIENT_BRANCH=${{ matrix.openstack_version }}
      - name: Checkout go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.15'
      - name: Run Gophercloud acceptance tests
        run: ./script/acceptancetest
        env:
          DEVSTACK_PATH: ${{ github.workspace }}/devstack
          ACCEPTANCE_TESTS_FILTER: "^.*clustering.*$"
      - name: Generate logs on failure
        run: ./script/collectlogs
        if: failure()
      - name: Upload logs artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: functional-clustering-${{ matrix.name }}
          path: /tmp/devstack-logs/*
