name: Verify PR Labels
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pierreprinetti/gobreaking@v0
