name: Linters
on:
  - merge_group
  - push
  - pull_request
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gophercloud
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Run linters
        run: |
          make lint
      - name: Ensure go.mod is up-to-date
        run: |
          if [ $(go mod tidy -diff | wc -l) -gt 0 ]; then git diff && exit 1; fi
