name: Linters
on:
  - merge_group
  - push
  - pull_request
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gophercloud
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Run linters
        run: |
          make lint
      - name: Ensure go.mod is up-to-date
        run: |
          if [ $(go mod tidy -diff | wc -l) -gt 0 ]; then git diff && exit 1; fi
